// app/layout.tsx  ← Server Component
import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Navbar'
import ThemeProviderWrapper from '@/utils/ThemeProviderWrapper'
import ThemeToggle from '@/components/ThemeToggle'
 // the new client component

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProviderWrapper>
          <Navbar />
          <ThemeToggle />      {/* wherever you want it */}
          {children}
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
