// app/layout.tsx  ← Server Component
import type { Metadata } from 'next'
import './globals.css'
import { Inter as FontInter } from 'next/font/google';
import Navbar from '@/components/Navbar'
import ThemeProviderWrapper from '@/utils/ThemeProviderWrapper'
import ThemeToggle from '@/components/ThemeToggle'
import  Footer  from '@/components/Footer'
 // the new client component
 const inter = FontInter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <ThemeProviderWrapper>
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-grow">
            {children}
          </main>
        </div>
      </ThemeProviderWrapper>
    </body>
  </html>
  );
}
